#!/usr/bin/env sh

cd $(dirname $0)/..

trap 'rm -f ${LOCK_FILE} ement' 0 1 2 3 6 9 15

LOCK_FILE="/tmp/process.lock"

if [[ -e ${LOCK_FILE} ]]; then
  echo "Have a running process, skip this round!"
else
  touch ${LOCK_FILE}
  echo "I will sleep 60 seconds"
  sleep 60
fi
